[package]
name = "ridl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
clap.workspace = true
ridl-core = { path = "../ridl-core" }
ridl-diff = { path = "../../tools/diff" }
ridl-fmt = { path = "../../tools/fmt" }
ridl-ir = { path = "../ridl-ir" }
ridlc = { path = "../ridlc" }

[dev-dependencies]
serde_json.workspace = true
