[package]
name = "ridl-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
codespan-reporting.workspace = true
ridl-ir = { path = "../ridl-ir" }
ridl-syntax = { path = "../ridl-syntax" }
rowan.workspace = true
salsa.workspace = true
serde.workspace = true

[dev-dependencies]
insta.workspace = true
