//! Generates the catalog-descriptor accessors
//! (`crates/ridl-descriptor/src/generated.rs`) from
//! `crates/ridl-descriptor/schema/catalog.fbs` with planus, the pure-Rust
//! FlatBuffers toolchain. No `flatc` binary is involved, for the same reason
//! the IR compiles through `protox`: the build must not depend on a tool the
//! toolchain pin does not cover (ADR-0009).
//!
//! The output is formatted by `rustfmt` at the workspace's edition, so the
//! committed file passes `cargo fmt --all --check` as generated. `rustfmt` is
//! a component of the pinned toolchain (`rust-toolchain.toml`), so the drift
//! test below and the formatting gate run the same formatter. The AST
//! generator in [`crate::codegen`] reaches the same property without
//! `rustfmt`, by emitting only shapes `prettyplease` and `rustfmt` agree on;
//! planus's output is not under this crate's control, so that route is not
//! open here.
//!
//! The drift test below fails whenever the committed output is stale, so the
//! accessors can never silently diverge from the schema.

use std::fs;
use std::io::Write as _;
use std::path::PathBuf;
use std::process::{Command, Stdio};

/// The header the generated file starts with. The lints are allowed because
/// the output is planus's, not ours, and `-D warnings` must not turn a
/// generator style change into a build failure.
const HEADER: &str = "//! Generated by `cargo xtask descriptor-codegen` from \
`crates/ridl-descriptor/schema/catalog.fbs`. Do not edit.\n\
#![allow(clippy::all, dead_code, unused_imports, missing_docs)]\n\n";

/// The edition `rustfmt` formats the output as: the workspace's
/// (`[workspace.package] edition` in the root `Cargo.toml`), which is the one
/// `cargo fmt` uses for `ridl-descriptor`.
const EDITION: &str = "2024";

/// The schema's path from the repository root, as the generated file names it.
const SCHEMA_FROM_ROOT: &str = "crates/ridl-descriptor/schema/catalog.fbs";

fn descriptor_crate_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../crates/ridl-descriptor")
        .canonicalize()
        .expect("the ridl-descriptor crate directory exists")
}

pub(crate) fn schema_path() -> PathBuf {
    descriptor_crate_dir().join("schema/catalog.fbs")
}

pub(crate) fn generated_path() -> PathBuf {
    descriptor_crate_dir().join("src/generated.rs")
}

/// Compiles the schema and returns the formatted Rust source.
pub(crate) fn generate() -> String {
    let declarations = planus_translation::translate_files(&[schema_path()])
        .expect("catalog.fbs is a valid FlatBuffers schema (planus printed why not)");
    let raw = planus_codegen::generate_rust(&declarations, false)
        .expect("planus generates Rust for catalog.fbs");
    let mut out = String::from(HEADER);
    out.push_str(&relative_schema_paths(&raw));
    rustfmt(&out)
}

/// planus writes the schema's path, as it was given, into a doc comment on
/// every generated item. That path is absolute here, so it names the
/// checkout's own directory, and the committed file would then differ on
/// every other machine and in every other worktree. Each occurrence is
/// replaced with the path from the repository root.
fn relative_schema_paths(raw: &str) -> String {
    let absolute = schema_path();
    let absolute = absolute.to_str().expect("the schema path is UTF-8");
    assert!(
        raw.contains(absolute),
        "planus no longer writes the schema path into its output; remove \
         `relative_schema_paths`"
    );
    raw.replace(absolute, SCHEMA_FROM_ROOT)
}

/// Formats `source` with the toolchain's `rustfmt`, reading standard input
/// and writing standard output. Run from this crate's directory, so rustup
/// selects the toolchain `rust-toolchain.toml` pins.
fn rustfmt(source: &str) -> String {
    let mut child = Command::new("rustfmt")
        .args(["--edition", EDITION, "--emit", "stdout"])
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("`rustfmt` runs (it is a component of the pinned toolchain)");
    child
        .stdin
        .take()
        .expect("rustfmt's standard input is piped")
        .write_all(source.as_bytes())
        .expect("write the generated source to rustfmt");
    let output = child.wait_with_output().expect("rustfmt finishes");
    assert!(
        output.status.success(),
        "rustfmt rejected the generated source:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("rustfmt prints UTF-8")
}

pub(crate) fn write_generated() -> PathBuf {
    let path = generated_path();
    fs::write(&path, generate()).expect("write generated.rs");
    path
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed accessors must match what the schema produces.
    #[test]
    fn committed_generated_accessors_match_the_schema() {
        let fresh = generate();
        let committed = fs::read_to_string(generated_path()).unwrap_or_default();
        assert!(
            fresh == committed,
            "crates/ridl-descriptor/src/generated.rs is stale — run `cargo xtask descriptor-codegen`",
        );
    }
}
