//! The typed AST node structs, generated from `typl.ungram`.
//!
//! @generated by `cargo xtask codegen` — do not edit by hand. The
//! xtask drift test regenerates this file into a buffer and fails
//! when the committed text differs.

use super::support;
use super::{AstChildren, AstNode, Backing, Definition, FieldType, StructMember};
use crate::syntax_kind::{SyntaxKind, SyntaxNode, SyntaxToken};
/// A `SourceFile` node (`typl.ungram` rule `SourceFile`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SourceFile {
    syntax: SyntaxNode,
}
impl AstNode for SourceFile {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::SourceFile).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SourceFile {
    pub fn package_decl(&self) -> Option<PackageDecl> {
        support::child(&self.syntax)
    }
    pub fn imports(&self) -> AstChildren<Import> {
        support::children(&self.syntax)
    }
    pub fn definitions(&self) -> AstChildren<Definition> {
        support::children(&self.syntax)
    }
}
/// A `PackageDecl` node (`typl.ungram` rule `PackageDecl`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PackageDecl {
    syntax: SyntaxNode,
}
impl AstNode for PackageDecl {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::PackageDecl).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PackageDecl {
    pub fn qualified_name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
    pub fn package_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::PackageKw)
    }
}
/// A `Import` node (`typl.ungram` rule `Import`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Import {
    syntax: SyntaxNode,
}
impl AstNode for Import {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::Import).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Import {
    pub fn qualified_name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
    pub fn alias(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn import_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::ImportKw)
    }
    pub fn as_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::AsKw)
    }
}
/// A `QualifiedName` node (`typl.ungram` rule `QualifiedName`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct QualifiedName {
    syntax: SyntaxNode,
}
impl AstNode for QualifiedName {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::QualifiedName).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl QualifiedName {
    pub fn ident_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Ident)
    }
    pub fn dot_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Dot)
    }
}
/// A `Name` node (`typl.ungram` rule `Name`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Name {
    syntax: SyntaxNode,
}
impl AstNode for Name {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::Name).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Name {
    pub fn ident_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Ident)
    }
}
/// A `TypeDef` node (`typl.ungram` rule `TypeDef`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TypeDef {
    syntax: SyntaxNode,
}
impl AstNode for TypeDef {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::TypeDef).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl TypeDef {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn backing(&self) -> Option<Backing> {
        support::child(&self.syntax)
    }
    pub fn constraint(&self) -> Option<Constraint> {
        support::child(&self.syntax)
    }
    pub fn init_value(&self) -> Option<InitValue> {
        support::child(&self.syntax)
    }
    pub fn internal_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::InternalKw)
    }
    pub fn error_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::ErrorKw)
    }
    pub fn type_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::TypeKw)
    }
    pub fn colon_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Colon)
    }
}
/// A `ConstDef` node (`typl.ungram` rule `ConstDef`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ConstDef {
    syntax: SyntaxNode,
}
impl AstNode for ConstDef {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::ConstDef).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ConstDef {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn type_ref(&self) -> Option<PathType> {
        support::child(&self.syntax)
    }
    pub fn value(&self) -> Option<Literal> {
        support::child(&self.syntax)
    }
    pub fn internal_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::InternalKw)
    }
    pub fn error_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::ErrorKw)
    }
    pub fn const_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::ConstKw)
    }
    pub fn colon_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Colon)
    }
    pub fn eq_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Eq)
    }
}
/// A `StructDef` node (`typl.ungram` rule `StructDef`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StructDef {
    syntax: SyntaxNode,
}
impl AstNode for StructDef {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::StructDef).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl StructDef {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn members(&self) -> AstChildren<StructMember> {
        support::children(&self.syntax)
    }
    pub fn internal_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::InternalKw)
    }
    pub fn error_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::ErrorKw)
    }
    pub fn struct_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::StructKw)
    }
    pub fn l_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::LBrace)
    }
    pub fn comma_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Comma)
    }
    pub fn r_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::RBrace)
    }
}
/// A `EnumDef` node (`typl.ungram` rule `EnumDef`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EnumDef {
    syntax: SyntaxNode,
}
impl AstNode for EnumDef {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::EnumDef).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl EnumDef {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn values(&self) -> AstChildren<EnumValue> {
        support::children(&self.syntax)
    }
    pub fn reserved(&self) -> AstChildren<ReservedEntry> {
        support::children(&self.syntax)
    }
    pub fn internal_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::InternalKw)
    }
    pub fn error_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::ErrorKw)
    }
    pub fn enum_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::EnumKw)
    }
    pub fn l_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::LBrace)
    }
    pub fn comma_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Comma)
    }
    pub fn r_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::RBrace)
    }
}
/// A `EnumSetDef` node (`typl.ungram` rule `EnumSetDef`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EnumSetDef {
    syntax: SyntaxNode,
}
impl AstNode for EnumSetDef {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::EnumSetDef).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl EnumSetDef {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn bits(&self) -> AstChildren<EnumSetBit> {
        support::children(&self.syntax)
    }
    pub fn backing_ref(&self) -> Option<PathType> {
        support::child(&self.syntax)
    }
    pub fn internal_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::InternalKw)
    }
    pub fn error_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::ErrorKw)
    }
    pub fn enumset_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::EnumsetKw)
    }
    pub fn l_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::LBrace)
    }
    pub fn comma_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Comma)
    }
    pub fn r_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::RBrace)
    }
    pub fn colon_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Colon)
    }
}
/// A `UnionDef` node (`typl.ungram` rule `UnionDef`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UnionDef {
    syntax: SyntaxNode,
}
impl AstNode for UnionDef {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::UnionDef).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl UnionDef {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn arms(&self) -> AstChildren<UnionArm> {
        support::children(&self.syntax)
    }
    pub fn reserved(&self) -> AstChildren<ReservedEntry> {
        support::children(&self.syntax)
    }
    pub fn internal_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::InternalKw)
    }
    pub fn error_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::ErrorKw)
    }
    pub fn union_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::UnionKw)
    }
    pub fn l_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::LBrace)
    }
    pub fn comma_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Comma)
    }
    pub fn r_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::RBrace)
    }
}
/// A `Constraint` node (`typl.ungram` rule `Constraint`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Constraint {
    syntax: SyntaxNode,
}
impl AstNode for Constraint {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::Constraint).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Constraint {
    pub fn len(&self) -> Option<Bound> {
        support::child(&self.syntax)
    }
    pub fn l_bracket_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::LBracket)
    }
    pub fn dotdot_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::DotDot)
    }
    pub fn step_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::StepKw)
    }
    pub fn match_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::MatchKw)
    }
    pub fn r_bracket_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::RBracket)
    }
}
/// A `InitValue` node (`typl.ungram` rule `InitValue`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct InitValue {
    syntax: SyntaxNode,
}
impl AstNode for InitValue {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::InitValue).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl InitValue {
    pub fn literal(&self) -> Option<Literal> {
        support::child(&self.syntax)
    }
    pub fn eq_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Eq)
    }
}
/// A `PrimitiveType` node (`typl.ungram` rule `PrimitiveType`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PrimitiveType {
    syntax: SyntaxNode,
}
impl AstNode for PrimitiveType {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::PrimitiveType).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PrimitiveType {
    pub fn constraint(&self) -> Option<Constraint> {
        support::child(&self.syntax)
    }
    pub fn boolean_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::BooleanKw)
    }
    pub fn integer_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::IntegerKw)
    }
    pub fn float_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::FloatKw)
    }
    pub fn string_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::StringKw)
    }
    pub fn bytes_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::BytesKw)
    }
}
/// A `UnitExpr` node (`typl.ungram` rule `UnitExpr`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UnitExpr {
    syntax: SyntaxNode,
}
impl AstNode for UnitExpr {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::UnitExpr).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl UnitExpr {
    pub fn ident_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Ident)
    }
    pub fn slash_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Slash)
    }
    pub fn dot_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Dot)
    }
    pub fn percent_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Percent)
    }
}
/// A `Literal` node (`typl.ungram` rule `Literal`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Literal {
    syntax: SyntaxNode,
}
impl AstNode for Literal {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::Literal).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Literal {
    pub fn minus_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Minus)
    }
    pub fn int_number_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::IntNumber)
    }
    pub fn float_number_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::FloatNumber)
    }
    pub fn string_lit_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::String)
    }
    pub fn true_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::TrueKw)
    }
    pub fn false_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::FalseKw)
    }
    pub fn regex_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Regex)
    }
    pub fn ident_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Ident)
    }
}
/// A `Bound` node (`typl.ungram` rule `Bound`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Bound {
    syntax: SyntaxNode,
}
impl AstNode for Bound {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::Bound).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Bound {
    pub fn min(&self) -> Option<Literal> {
        support::nth_child(&self.syntax, 0usize)
    }
    pub fn max(&self) -> Option<Literal> {
        support::nth_child(&self.syntax, 1usize)
    }
    pub fn dotdot_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::DotDot)
    }
}
/// A `PathType` node (`typl.ungram` rule `PathType`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PathType {
    syntax: SyntaxNode,
}
impl AstNode for PathType {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::PathType).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PathType {
    pub fn qualified_name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
}
/// A `FieldDef` node (`typl.ungram` rule `FieldDef`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FieldDef {
    syntax: SyntaxNode,
}
impl AstNode for FieldDef {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::FieldDef).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl FieldDef {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn field_type(&self) -> Option<FieldType> {
        support::child(&self.syntax)
    }
    pub fn init_value(&self) -> Option<InitValue> {
        support::child(&self.syntax)
    }
    pub fn colon_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Colon)
    }
}
/// A `ReservedEntry` node (`typl.ungram` rule `ReservedEntry`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ReservedEntry {
    syntax: SyntaxNode,
}
impl AstNode for ReservedEntry {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::ReservedEntry).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ReservedEntry {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn literal(&self) -> Option<Literal> {
        support::child(&self.syntax)
    }
    pub fn reserved_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::ReservedKw)
    }
}
/// A `TupleType` node (`typl.ungram` rule `TupleType`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TupleType {
    syntax: SyntaxNode,
}
impl AstNode for TupleType {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::TupleType).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl TupleType {
    pub fn fields(&self) -> AstChildren<TupleField> {
        support::children(&self.syntax)
    }
    pub fn l_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::LParen)
    }
    pub fn comma_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Comma)
    }
    pub fn r_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::RParen)
    }
}
/// A `ArrayType` node (`typl.ungram` rule `ArrayType`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArrayType {
    syntax: SyntaxNode,
}
impl AstNode for ArrayType {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::ArrayType).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ArrayType {
    pub fn element(&self) -> Option<FieldType> {
        support::child(&self.syntax)
    }
    pub fn bound(&self) -> Option<Bound> {
        support::child(&self.syntax)
    }
    pub fn l_bracket_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::LBracket)
    }
    pub fn semicolon_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Semicolon)
    }
    pub fn r_bracket_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::RBracket)
    }
}
/// A `MapType` node (`typl.ungram` rule `MapType`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MapType {
    syntax: SyntaxNode,
}
impl AstNode for MapType {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::MapType).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl MapType {
    pub fn key(&self) -> Option<FieldType> {
        support::nth_child(&self.syntax, 0usize)
    }
    pub fn value(&self) -> Option<FieldType> {
        support::nth_child(&self.syntax, 1usize)
    }
    pub fn bound(&self) -> Option<Bound> {
        support::child(&self.syntax)
    }
    pub fn l_bracket_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::LBracket)
    }
    pub fn colon_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Colon)
    }
    pub fn semicolon_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Semicolon)
    }
    pub fn r_bracket_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::RBracket)
    }
}
/// A `OptionalType` node (`typl.ungram` rule `OptionalType`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct OptionalType {
    syntax: SyntaxNode,
}
impl AstNode for OptionalType {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::OptionalType).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl OptionalType {
    pub fn field_type(&self) -> Option<FieldType> {
        support::child(&self.syntax)
    }
    pub fn question_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Question)
    }
}
/// A `TupleField` node (`typl.ungram` rule `TupleField`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TupleField {
    syntax: SyntaxNode,
}
impl AstNode for TupleField {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::TupleField).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl TupleField {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn field_type(&self) -> Option<FieldType> {
        support::child(&self.syntax)
    }
    pub fn colon_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Colon)
    }
}
/// A `EnumValue` node (`typl.ungram` rule `EnumValue`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EnumValue {
    syntax: SyntaxNode,
}
impl AstNode for EnumValue {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::EnumValue).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl EnumValue {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn value(&self) -> Option<Literal> {
        support::child(&self.syntax)
    }
    pub fn eq_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Eq)
    }
}
/// A `EnumSetBit` node (`typl.ungram` rule `EnumSetBit`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EnumSetBit {
    syntax: SyntaxNode,
}
impl AstNode for EnumSetBit {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::EnumSetBit).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl EnumSetBit {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn value(&self) -> Option<Literal> {
        support::child(&self.syntax)
    }
    pub fn eq_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Eq)
    }
}
/// A `UnionArm` node (`typl.ungram` rule `UnionArm`).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UnionArm {
    syntax: SyntaxNode,
}
impl AstNode for UnionArm {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::UnionArm).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl UnionArm {
    pub fn name(&self) -> Option<Name> {
        support::child(&self.syntax)
    }
    pub fn type_ref(&self) -> Option<PathType> {
        support::child(&self.syntax)
    }
    pub fn colon_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::Colon)
    }
}
/// An error-recovery node wrapping the tokens the parser skipped
/// (task E1.2c). The one node kind with no rule in `typl.ungram`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ErrorNode {
    syntax: SyntaxNode,
}
impl AstNode for ErrorNode {
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::ErrorNode).then_some(Self { syntax })
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
