//! Every text file `ridl build` generates begins with the `@generated` marker
//! and, when the manifest names a `[codegen] header-file`, the header text.
//! JSON outputs carry neither, because the format cannot hold a comment.

use std::path::Path;

use ridlc::Emit;

const TEXT_EMITS: [Emit; 4] = [Emit::Rust, Emit::TypeScript, Emit::Proto, Emit::Flatbuffers];

/// Writes a package `acme.demo` into `dir`, with an optional header file. The
/// package names `ridl.std`'s `Name`, so a build also writes `ridl.std`'s output.
fn write_package(dir: &Path, header: Option<&str>) {
    let codegen = if header.is_some() {
        "\n[codegen]\nheader-file = \"H.txt\"\n"
    } else {
        ""
    };
    std::fs::write(
        dir.join("ridl.toml"),
        format!("[package]\nname = \"acme.demo\"\nversion = \"1.0.0\"\n{codegen}"),
    )
    .expect("the manifest is written");
    if let Some(header) = header {
        std::fs::write(dir.join("H.txt"), header).expect("the header file is written");
    }
    std::fs::write(
        dir.join("demo.typl"),
        "package acme.demo\n\n/// Vehicle speed over ground\ntype Speed : km/h [0.0..250.0 step 0.5]\n\nstruct Owner {\n  name : Name\n}\n",
    )
    .expect("the source is written");
}

fn build(entry: &Path, out: &Path, emits: &[Emit]) {
    let run = ridlc::run_build(entry, out, emits, false.into()).expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );
}

const MARKER: &str = "// @generated by ridl from package acme.demo. Do not edit.\n";

#[test]
fn every_generated_text_file_begins_with_the_marker() {
    let src = tempfile::tempdir().expect("temp dir");
    let out = tempfile::tempdir().expect("temp dir");
    write_package(
        src.path(),
        Some("Copyright Acme\nSPDX-License-Identifier: MIT"),
    );
    build(src.path(), out.path(), &TEXT_EMITS);

    let preamble = format!("{MARKER}// Copyright Acme\n// SPDX-License-Identifier: MIT\n\n");
    for name in [
        "acme.demo.rs",
        "acme.demo.ts",
        "acme.demo.proto",
        "acme.demo.fbs",
    ] {
        let text = std::fs::read_to_string(out.path().join(name)).expect("the file is written");
        let rest = text
            .strip_prefix(&preamble)
            .unwrap_or_else(|| panic!("{name} does not begin with the preamble:\n{text}"));
        if name.ends_with(".ts") {
            assert!(
                rest.starts_with("/* eslint-disable */\n\n"),
                "{name}:\n{rest}"
            );
        }
    }
}

/// The outputs for `ridl.std`, which a package that names its types makes the
/// build write, carry the same header as the package outputs.
#[test]
fn the_ridl_std_outputs_carry_the_header() {
    let src = tempfile::tempdir().expect("temp dir");
    let out = tempfile::tempdir().expect("temp dir");
    write_package(src.path(), Some("Copyright Acme"));
    build(src.path(), out.path(), &[Emit::Rust]);

    let text = std::fs::read_to_string(out.path().join("ridl.std.rs"))
        .expect("the build writes ridl.std.rs");
    let preamble =
        "// @generated by ridl from package ridl.std. Do not edit.\n// Copyright Acme\n\n";
    assert!(text.starts_with(preamble), "{text}");
}

#[test]
fn no_header_file_gives_the_marker_alone() {
    let src = tempfile::tempdir().expect("temp dir");
    let out = tempfile::tempdir().expect("temp dir");
    write_package(src.path(), None);
    build(src.path(), out.path(), &TEXT_EMITS);

    let preamble = format!("{MARKER}\n");
    for name in [
        "acme.demo.rs",
        "acme.demo.ts",
        "acme.demo.proto",
        "acme.demo.fbs",
    ] {
        let text = std::fs::read_to_string(out.path().join(name)).expect("the file is written");
        let rest = text
            .strip_prefix(&preamble)
            .unwrap_or_else(|| panic!("{name} does not begin with the marker:\n{text}"));
        assert!(!rest.starts_with('\n'), "{name} has two blank lines");
    }
}

#[test]
fn single_file_mode_names_the_declared_package() {
    let src = tempfile::tempdir().expect("temp dir");
    let out = tempfile::tempdir().expect("temp dir");
    let file = src.path().join("stem.typl");
    std::fs::write(
        &file,
        "package acme.single\n\n/// Vehicle speed over ground\ntype Speed : km/h [0.0..250.0 step 0.5]\n",
    )
    .expect("the source is written");
    build(&file, out.path(), &[Emit::Rust]);

    let text = std::fs::read_to_string(out.path().join("stem.rs")).expect("stem.rs is written");
    let mut lines = text.lines();
    assert_eq!(
        lines.next(),
        Some("// @generated by ridl from package acme.single. Do not edit.")
    );
    assert_eq!(lines.next(), Some(""), "no header text follows the marker");
    // The preamble is line comments only, so wrapping the file in a module
    // through `include!` keeps it valid.
    let preamble: Vec<&str> = text.lines().take_while(|line| !line.is_empty()).collect();
    assert!(
        preamble.iter().all(|line| line.starts_with("//")),
        "{preamble:?}"
    );
}

#[test]
fn codegen_model_output_carries_no_marker() {
    let src = tempfile::tempdir().expect("temp dir");
    let out = tempfile::tempdir().expect("temp dir");
    write_package(src.path(), Some("Copyright Acme"));
    build(src.path(), out.path(), &[Emit::CodegenModel]);

    let text = std::fs::read_to_string(out.path().join("acme.demo.codegen.json"))
        .expect("the model is written");
    serde_json::from_str::<serde_json::Value>(&text).expect("the model is valid JSON");
    assert!(!text.contains("@generated"), "{text}");
}
