//! `--emit rust` writes a compiling crate (Task 7,
//! docs/wip/typl-value-objects-plan.md): a `Cargo.toml` and `lib.rs` alongside
//! the per-package `.rs` files, so the flat emitted files resolve at the
//! `crate::…` paths `ridl_backend_rust::type_path` already generates.

use std::path::{Path, PathBuf};

use ridlc::Emit;

/// Writes a one-package fixture (a `ridl.toml` naming `package_name` and one
/// source file) into `dir` and returns the package directory, for the package
/// shapes no corpus fixture has: a name whose segment is a Rust keyword, a
/// single-segment name, and a package whose Rust generation fails.
fn write_package_fixture(dir: &Path, package_name: &str, source: &str) -> PathBuf {
    let package_dir = dir.join("pkg");
    std::fs::create_dir_all(&package_dir).expect("the package directory is created");
    std::fs::write(
        package_dir.join("ridl.toml"),
        format!("[package]\nname = \"{package_name}\"\nversion = \"1.0.0\"\n"),
    )
    .expect("the manifest is written");
    std::fs::write(package_dir.join("source.typl"), source).expect("the source is written");
    package_dir
}

/// Compiles `<dir>/lib.rs` as a crate root with `rustc`, which is the only
/// thing that proves a module tree resolves. Panics with the crate root's own
/// text when it does not compile.
fn compile_crate_root(dir: &Path) {
    let status = std::process::Command::new("rustc")
        .current_dir(dir)
        .args([
            "--edition",
            "2024",
            "--crate-type",
            "lib",
            "--emit",
            "metadata",
            "-o",
        ])
        .arg(dir.join("out.rmeta"))
        .arg("lib.rs")
        .status()
        .expect("rustc must be installed and runnable for this test to be meaningful");
    let lib = std::fs::read_to_string(dir.join("lib.rs")).unwrap_or_default();
    assert!(
        status.success(),
        "the emitted crate root must compile, lib.rs was:\n{lib}"
    );
}

/// Every file named by a `#[path = "…"]` attribute in a generated crate root,
/// in the order they appear. The inline-module anchor `#[path = "."]` is not
/// one: it names the output directory, not a file.
fn path_attribute_targets(lib: &str) -> Vec<String> {
    const OPEN: &str = "#[path = \"";
    lib.match_indices(OPEN)
        .map(|(index, _)| {
            let rest = &lib[index + OPEN.len()..];
            let end = rest.find('"').expect("a path attribute is closed");
            rest[..end].to_string()
        })
        .filter(|target| target != ".")
        .collect()
}

/// `run_build` over a multi-package workspace with `&[Emit::Rust]` writes a
/// `Cargo.toml` and a `lib.rs` alongside the per-package sources, and the
/// manifest carries the `validate-pattern`/`std` feature set and the `regex`
/// and `ridl-rt` dependencies the plan specifies.
#[test]
fn rust_emit_writes_a_compiling_crate() {
    let out = tempfile::tempdir().expect("temp dir");
    let run = ridlc::run_build(
        Path::new("tests/corpus/workspace-two-members"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    assert!(out.path().join("Cargo.toml").exists());
    assert!(out.path().join("lib.rs").exists());

    let manifest = std::fs::read_to_string(out.path().join("Cargo.toml")).unwrap();
    assert!(manifest.contains("default = [\"validate-pattern\", \"std\"]"));
    assert!(manifest.contains("regex = { version = \"1\", optional = true }"));
    assert!(manifest.contains("ridl-rt = "));

    let lib = std::fs::read_to_string(out.path().join("lib.rs")).unwrap();
    assert!(lib.contains("pub mod veh"), "lib.rs was:\n{lib}");
}

/// Both generated files begin with their own generated-by marker. The two
/// lines are load-bearing rather than decorative: a build refuses to overwrite
/// a `lib.rs` or a `Cargo.toml` that does not begin with them
/// (`refusing_to_overwrite_*` below), so a renderer that stopped writing one
/// would turn every subsequent build of the same output directory into a
/// refusal.
#[test]
fn both_generated_files_carry_their_generated_by_marker() {
    let out = tempfile::tempdir().expect("temp dir");
    let run = ridlc::run_build(
        Path::new("tests/corpus/workspace-two-members"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    let lib = std::fs::read_to_string(out.path().join("lib.rs")).unwrap();
    assert!(
        lib.starts_with("// Generated by ridlc. Do not edit.\n"),
        "lib.rs must open with the crate-root marker, was:\n{lib}"
    );
    let manifest = std::fs::read_to_string(out.path().join("Cargo.toml")).unwrap();
    assert!(
        manifest.starts_with("# Generated by ridlc. Do not edit.\n"),
        "Cargo.toml must open with the manifest marker, was:\n{manifest}"
    );
}

/// THE INVARIANT. Every assertion above names one file by hand, so a package
/// silently dropped from the module tree passes all of them — and passes the
/// `rustc` proof too, which happily compiles a crate root that merely omits a
/// module. This states the property instead, in both directions: every
/// emitted `.rs` file is named by exactly one `#[path]` in the crate root, and
/// every `#[path]` in the crate root names a file that exists.
#[test]
fn every_emitted_file_is_named_exactly_once_in_the_crate_root() {
    let out = tempfile::tempdir().expect("temp dir");
    let run = ridlc::run_build(
        Path::new("tests/corpus/workspace-two-members"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    let lib = std::fs::read_to_string(out.path().join("lib.rs")).unwrap();
    let targets = path_attribute_targets(&lib);

    let mut emitted: Vec<String> = std::fs::read_dir(out.path())
        .expect("the output directory is readable")
        .map(|entry| entry.expect("a directory entry is readable").file_name())
        .map(|name| name.to_string_lossy().into_owned())
        .filter(|name| name.ends_with(".rs") && name != "lib.rs")
        .collect();
    emitted.sort();
    assert!(
        emitted.len() > 1,
        "the fixture must emit several packages, or this test proves nothing, got: {emitted:?}"
    );

    for file in &emitted {
        let named = targets.iter().filter(|target| *target == file).count();
        assert_eq!(
            named, 1,
            "`{file}` must be named by exactly one #[path] in the crate root, it is named \
             {named} times; lib.rs was:\n{lib}"
        );
    }
    for target in &targets {
        assert!(
            out.path().join(target).exists(),
            "the crate root names `{target}`, which no build wrote; lib.rs was:\n{lib}"
        );
    }
}

/// The emitted manifest is parsed as TOML and asserted as structure, not as a
/// handful of substrings: a `[lib]` section deleted, an `edition` changed, a
/// `[dependencies]` header deleted so both dependencies become feature keys,
/// a feature deleted while `default` still names it, or a feature list emptied
/// all leave every substring assertion above passing, and each of them breaks
/// the crate the build claims to have written.
#[test]
fn the_emitted_manifest_parses_and_carries_the_declared_structure() {
    use std::collections::BTreeMap;

    #[derive(serde::Deserialize)]
    struct GeneratedManifest {
        package: GeneratedPackage,
        lib: GeneratedLib,
        features: BTreeMap<String, Vec<String>>,
        dependencies: BTreeMap<String, Dependency>,
    }
    #[derive(serde::Deserialize)]
    struct GeneratedPackage {
        name: String,
        edition: String,
    }
    #[derive(serde::Deserialize)]
    struct GeneratedLib {
        path: String,
    }
    #[derive(serde::Deserialize)]
    #[serde(untagged)]
    enum Dependency {
        Plain(String),
        Detailed {
            version: String,
            #[serde(default)]
            optional: bool,
        },
    }
    impl Dependency {
        fn version(&self) -> &str {
            match self {
                Dependency::Plain(version) => version,
                Dependency::Detailed { version, .. } => version,
            }
        }
        fn optional(&self) -> bool {
            match self {
                Dependency::Plain(_) => false,
                Dependency::Detailed { optional, .. } => *optional,
            }
        }
    }

    let out = tempfile::tempdir().expect("temp dir");
    let run = ridlc::run_build(
        Path::new("tests/corpus/veh-common"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    let text = std::fs::read_to_string(out.path().join("Cargo.toml")).unwrap();
    let manifest: GeneratedManifest = toml::from_str(&text)
        .unwrap_or_else(|err| panic!("the manifest must parse: {err}\n{text}"));

    assert_eq!(manifest.package.name, "veh_common");
    assert_eq!(
        manifest.package.edition, "2024",
        "the generated code is edition 2024"
    );
    assert_eq!(
        manifest.lib.path, "lib.rs",
        "the crate root is the generated lib.rs, not src/lib.rs"
    );

    let features: BTreeMap<String, Vec<String>> = manifest.features;
    assert_eq!(
        features.keys().collect::<Vec<_>>(),
        vec!["default", "std", "validate-pattern"],
        "the feature table must hold exactly these three features, was: {features:?}"
    );
    assert_eq!(
        features["default"],
        vec!["validate-pattern".to_string(), "std".to_string()],
        "both features are on by default"
    );
    assert_eq!(
        features["validate-pattern"],
        vec!["dep:regex".to_string()],
        "the feature must actually enable the optional regex dependency"
    );
    assert!(
        features["std"].is_empty(),
        "`std` gates generated code only, it enables no dependency"
    );

    let dependencies = manifest.dependencies;
    assert_eq!(
        dependencies.keys().collect::<Vec<_>>(),
        vec!["regex", "ridl-rt"],
        "the generated crate depends on exactly these two crates, was: {:?}",
        dependencies.keys().collect::<Vec<_>>()
    );
    assert!(
        dependencies["regex"].optional(),
        "regex is optional — `validate-pattern` is what enables it"
    );
    assert_eq!(
        dependencies["regex"].version(),
        "1",
        "the regex requirement is the major version alone"
    );
    assert!(
        !dependencies["ridl-rt"].optional(),
        "ridl-rt is not optional: every generated constructor names it"
    );
    assert!(
        !dependencies["ridl-rt"].version().is_empty(),
        "ridl-rt carries a version requirement; \
         `ridl_rt_version_requirement_matches_the_crate` pins which one"
    );
}

/// A typl package segment may be a Rust keyword — `is_valid_name_segment`
/// accepts any lowercase segment, so `veh.mod` is a legal package name. The
/// crate root must escape it the same way `ridl_backend_rust::type_path`
/// escapes it in a cross-package reference, which is what
/// `ridl_backend_rust::module_segment` is for. Written raw, the crate root
/// says `pub mod mod;` and does not even parse.
#[test]
fn a_keyword_package_segment_emits_a_crate_root_that_compiles() {
    let fixture = tempfile::tempdir().expect("temp fixture dir");
    let entry = write_package_fixture(
        fixture.path(),
        "veh.mod",
        "package veh.mod\n\ntype Speed : km/h [0.0..250.0 step 0.5]\n",
    );

    let out = tempfile::tempdir().expect("temp dir");
    let run =
        ridlc::run_build(&entry, out.path(), &[Emit::Rust], false.into()).expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    let lib = std::fs::read_to_string(out.path().join("lib.rs")).unwrap();
    assert!(
        lib.contains("pub mod r#mod;"),
        "the keyword segment must be escaped as a raw identifier, lib.rs was:\n{lib}"
    );
    compile_crate_root(out.path());
}

/// A single-segment package name (`app`) is a leaf at depth 0 — the most
/// common real shape, and the one every other test misses, because every name
/// they reach the crate root with is dotted.
#[test]
fn a_single_segment_package_emits_a_crate_root_that_compiles() {
    let fixture = tempfile::tempdir().expect("temp fixture dir");
    let entry = write_package_fixture(
        fixture.path(),
        "app",
        "package app\n\ntype Speed : km/h [0.0..250.0 step 0.5]\n",
    );

    let out = tempfile::tempdir().expect("temp dir");
    let run =
        ridlc::run_build(&entry, out.path(), &[Emit::Rust], false.into()).expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    let lib = std::fs::read_to_string(out.path().join("lib.rs")).unwrap();
    assert!(
        lib.contains("#[path = \"app.rs\"]") && lib.contains("pub mod app;"),
        "a depth-0 leaf must be a plain module, lib.rs was:\n{lib}"
    );
    compile_crate_root(out.path());
}

/// A package that checks clean but whose Rust generation fails makes the build
/// skip that package's `.rs` and record a diagnostic instead. The module tree
/// is built from every checked package, so it would name a file that was never
/// written — the crate root would not compile. Neither generated file is
/// written when any error-severity diagnostic is present after the write loop.
///
/// The failure used here is the generated-name collision between two tuple
/// types (`ridl_backend_rust::tuple_collision`): `AB.c` and `A.bC` both reach
/// the induced struct name `ABC`, and the two tuples have different shapes, so
/// the backend refuses the package. Nothing upstream draws a diagnostic for
/// it, which is exactly why the emit gate computed before the write loop
/// cannot see it.
#[test]
fn a_package_that_fails_rust_generation_writes_no_crate_files() {
    let fixture = tempfile::tempdir().expect("temp fixture dir");
    let entry = write_package_fixture(
        fixture.path(),
        "app",
        "package app\n\nstruct AB {\n  c : (x: integer)\n}\n\nstruct A {\n  bC : (y: integer)\n}\n",
    );

    let out = tempfile::tempdir().expect("temp dir");
    let run =
        ridlc::run_build(&entry, out.path(), &[Emit::Rust], false.into()).expect("build runs");
    assert!(
        run.has_error(),
        "the fixture must fail Rust generation, or this test proves nothing, got: {:?}",
        run.diagnostics
    );

    assert!(
        !out.path().join("app.rs").exists(),
        "the failing package writes no source"
    );
    assert!(
        !out.path().join("lib.rs").exists(),
        "a crate root naming a file no build wrote does not compile, so none is written"
    );
    assert!(
        !out.path().join("Cargo.toml").exists(),
        "a manifest without a crate root is not a crate"
    );
}

/// `lib.rs` and `Cargo.toml` are not package-scoped names and `--out-dir` is
/// any directory the caller names, including the root of a hand-written crate.
/// `std::fs::write` truncates, so a build must check before it writes: a file
/// that does not begin with its generated-by marker is left exactly as it is,
/// and neither file is written.
#[test]
fn a_hand_written_crate_root_is_refused_and_left_untouched() {
    let out = tempfile::tempdir().expect("temp dir");
    let hand_written = "//! A crate a person wrote.\npub fn main_logic() {}\n";
    std::fs::write(out.path().join("lib.rs"), hand_written).expect("the crate root is written");

    let run = ridlc::run_build(
        Path::new("tests/corpus/veh-common"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");

    assert!(
        run.has_error(),
        "overwriting a hand-written file is an error, got: {:?}",
        run.diagnostics
    );
    let message = run
        .diagnostics
        .iter()
        .map(|diagnostic| diagnostic.message.clone())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        message.contains("lib.rs") && message.contains("ridlc did not write it"),
        "the diagnostic must name the file and say it was not written, got:\n{message}"
    );

    assert_eq!(
        std::fs::read_to_string(out.path().join("lib.rs")).unwrap(),
        hand_written,
        "the hand-written crate root must be byte-identical"
    );
    assert!(
        !out.path().join("Cargo.toml").exists(),
        "a refusal on either file writes neither"
    );
}

/// The manifest half of the same rule: a hand-written `Cargo.toml` is refused
/// and no crate root is written next to it.
#[test]
fn a_hand_written_manifest_is_refused_and_left_untouched() {
    let out = tempfile::tempdir().expect("temp dir");
    let hand_written = "[package]\nname = \"written_by_a_person\"\nversion = \"0.1.0\"\n";
    std::fs::write(out.path().join("Cargo.toml"), hand_written).expect("the manifest is written");

    let run = ridlc::run_build(
        Path::new("tests/corpus/veh-common"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");

    assert!(
        run.has_error(),
        "overwriting a hand-written file is an error, got: {:?}",
        run.diagnostics
    );
    assert_eq!(
        std::fs::read_to_string(out.path().join("Cargo.toml")).unwrap(),
        hand_written,
        "the hand-written manifest must be byte-identical"
    );
    assert!(
        !out.path().join("lib.rs").exists(),
        "a refusal on either file writes neither"
    );
}

/// The other direction: a file a previous build wrote carries the marker, so
/// rebuilding into the same output directory overwrites it. Without this, the
/// refusal above would make a second build of any output directory fail.
#[test]
fn a_previously_generated_crate_root_is_overwritten() {
    let out = tempfile::tempdir().expect("temp dir");
    std::fs::write(
        out.path().join("lib.rs"),
        "// Generated by ridlc. Do not edit.\n\n// stale content from an earlier build\n",
    )
    .expect("the stale crate root is written");
    std::fs::write(
        out.path().join("Cargo.toml"),
        "# Generated by ridlc. Do not edit.\n[package]\nname = \"stale\"\n",
    )
    .expect("the stale manifest is written");

    let run = ridlc::run_build(
        Path::new("tests/corpus/veh-common"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    let lib = std::fs::read_to_string(out.path().join("lib.rs")).unwrap();
    assert!(
        !lib.contains("stale content") && lib.contains("#[path = \"veh.common.rs\"]"),
        "a marked crate root is overwritten, was:\n{lib}"
    );
    let manifest = std::fs::read_to_string(out.path().join("Cargo.toml")).unwrap();
    assert!(
        manifest.contains("name = \"veh_common\""),
        "a marked manifest is overwritten, was:\n{manifest}"
    );
}

/// THE REAL PROOF: the emitted crate root actually compiles with `rustc`,
/// which is the only thing that proves the module tree resolves — including
/// every `crate::…` cross-package reference the packages make to each other.
/// This deliberately does not pass `--extern ridl_rt`: nothing generated names
/// the runtime crate until Task 3 lands, so the argument would be inert and
/// would hide an `E0433` if generated code named `ridl_rt` when it should not
/// yet. Task 3 adds `--extern ridl_rt` to this test.
#[test]
fn emitted_lib_rs_compiles_with_rustc() {
    let out = tempfile::tempdir().expect("temp dir");
    let run = ridlc::run_build(
        Path::new("tests/corpus/veh-cluster"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    compile_crate_root(out.path());
}

/// A package referencing `ridl.std` makes the build write `ridl.std.rs`
/// (issue #190); `lib.rs` must make it reachable as `crate::ridl::std`, or the
/// crate the other packages reference from does not compile.
#[test]
fn ridl_std_is_reachable_from_lib_rs() {
    let out = tempfile::tempdir().expect("temp dir");
    let run = ridlc::run_build(
        Path::new("tests/corpus/veh-common"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    assert!(
        out.path().join("ridl.std.rs").exists(),
        "the fixture references ridl.std, so the build must write ridl.std.rs"
    );

    let lib = std::fs::read_to_string(out.path().join("lib.rs")).unwrap();
    assert!(
        lib.contains("#[path = \"ridl.std.rs\"]") && lib.contains("pub mod std"),
        "lib.rs must make ridl.std.rs reachable as crate::ridl::std, was:\n{lib}"
    );
}

/// Single-file mode (no manifest anywhere up the tree) keeps writing only
/// `<stem>.rs`, matching the documented single-file asymmetry on
/// `Emit::TypeScript` — it never writes `Cargo.toml` or `lib.rs`.
#[test]
fn single_file_mode_writes_neither_manifest_nor_lib_rs() {
    let out = tempfile::tempdir().expect("temp dir");
    let entry_dir = tempfile::tempdir().expect("temp entry dir");
    let entry = entry_dir.path().join("standalone.typl");
    std::fs::write(
        &entry,
        "package standalone\ntype Speed: km/h [0.0..250.0 step 0.5]\n",
    )
    .unwrap();

    let run =
        ridlc::run_build(&entry, out.path(), &[Emit::Rust], false.into()).expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    assert!(out.path().join("standalone.rs").exists());
    assert!(!out.path().join("Cargo.toml").exists());
    assert!(!out.path().join("lib.rs").exists());
}

/// The generated crate name comes from the manifest's `[package]` name with
/// every `.` replaced by `_`, since a dotted ridl package name (`veh.common`)
/// is not a legal Cargo package name.
#[test]
fn crate_name_replaces_dots_with_underscores() {
    let out = tempfile::tempdir().expect("temp dir");
    let run = ridlc::run_build(
        Path::new("tests/corpus/veh-common"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    let manifest = std::fs::read_to_string(out.path().join("Cargo.toml")).unwrap();
    assert!(
        manifest.contains("name = \"veh_common\""),
        "manifest was:\n{manifest}"
    );
}

/// A `[workspace]` manifest names no package, so the generated crate falls
/// back to `ridl_generated`.
#[test]
fn crate_name_falls_back_for_a_workspace_manifest() {
    let out = tempfile::tempdir().expect("temp dir");
    let run = ridlc::run_build(
        Path::new("tests/corpus/workspace-two-members"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );

    let manifest = std::fs::read_to_string(out.path().join("Cargo.toml")).unwrap();
    assert!(
        manifest.contains("name = \"ridl_generated\""),
        "manifest was:\n{manifest}"
    );
}

/// The `ridl-rt` dependency requirement in the emitted manifest and
/// `crates/ridl-rt`'s own version must agree on major and minor, or the
/// generated crate could pin a `ridl-rt` release that predates the API the
/// codegen it emits actually needs. `ridlc` cannot read
/// `crates/ridl-rt/Cargo.toml` at run time — it is an installed binary with no
/// access to this repository's sources — so the manifest string is a literal;
/// this test is what keeps the literal and the crate's real version from
/// drifting apart silently (Task 7's own rationale for reading the version at
/// emit time, redirected into a guard test instead).
#[test]
fn ridl_rt_version_requirement_matches_the_crate() {
    #[derive(serde::Deserialize)]
    struct CargoManifest {
        package: CargoPackage,
    }
    #[derive(serde::Deserialize)]
    struct CargoPackage {
        version: String,
    }

    let ridl_rt_manifest_text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../ridl-rt/Cargo.toml"
    ))
    .expect("crates/ridl-rt/Cargo.toml must exist");
    let ridl_rt_manifest: CargoManifest = toml::from_str(&ridl_rt_manifest_text)
        .expect("crates/ridl-rt/Cargo.toml must be valid TOML");
    let version = ridl_rt_manifest.package.version;
    let mut segments = version.split('.');
    let major = segments
        .next()
        .expect("a semver version has a major segment");
    let minor = segments
        .next()
        .expect("a semver version has a minor segment");
    let expected = format!("ridl-rt = \"{major}.{minor}\"");

    let out = tempfile::tempdir().expect("temp dir");
    let run = ridlc::run_build(
        Path::new("tests/corpus/veh-common"),
        out.path(),
        &[Emit::Rust],
        false.into(),
    )
    .expect("build runs");
    assert!(
        !run.has_error(),
        "expected no error, got: {:?}",
        run.diagnostics
    );
    let manifest = std::fs::read_to_string(out.path().join("Cargo.toml")).unwrap();
    assert!(
        manifest.contains(&expected),
        "expected `{expected}` in the emitted manifest, got:\n{manifest}"
    );
}
